package product

import (
	"os/exec"
)

func (p *Product) GetHTML() ([]byte, error) {
	return GetHTMLFromID(p.CSCode)
}

func GetHTMLFromID(id string) ([]byte, error) {
	return getHTMLFromIDWithCURL(id)
}

func getHTMLFromIDWithCURL(id string) ([]byte, error) {
	//cmd := exec.Command("./curl_cscode.sh")
	//cmd.Env = append(os.Environ(),
	//    "ITEM_ID="+id,
	//)

	cmd := exec.Command("curl",
		"https://webapps2.abc.utah.gov/Production/OnlineInventoryQuery/IQ/InventoryQuery.aspx",
		"--data", "ctl00%24ContentPlaceHolderBody%24tbCscCode="+id,
		"--data", "__VIEWSTATE=%2FwEPDwUKLTczNzAyOTQ2NQ9kFgJmD2QWAgIDD2QWAgIFD2QWAgIDD2QWAgIBD2QWAmYPZBYGAgMPZBYGAgEPZBYCAgMPDxYCHgRUZXh0ZWRkAgMPZBYCAgMPDxYCHwBlZGQCBQ8PFgIfAAUPVmVyc2lvbiBBWCA3OTI4ZGQCBQ8PFgIeB1Zpc2libGVnZBYQAgEPZBYEAgMPDxYCHwAFAzU1MmRkAgcPDxYCHwAFATBkZAIFDw8WAh8ABQYwODcwMTRkZAIHDw8WAh8ABShCQVNJTCBIQVlERU4gQ0FSSUJCRUFOIFJFU0VSVkUgUllFIDc1MG1sZGQCCw8PFgIfAAUnQSAgTGltaXRlZCBEaXN0IHdpdGggQWxsb2NhdGVkIFF1YW50aXR5ZGQCDQ8PFgIfAAUQT25lIFBlciBDdXN0b21lcmRkAhEPDxYCHwAFBiQ0Ny45OWRkAhMPDxYCHwAFGiBhcyBvZiBGcmlkYXkgTWF5IDMxLCAyMDE5ZGQCFw9kFgICAQ88KwARAwAPFgQeC18hRGF0YUJvdW5kZx4LXyFJdGVtQ291bnRmZAEQFgAWABYADBQrAABkAgwPZBYCAgEPZBYCAhMPZBYCAgEPZBYCAgEPZBYCAgcPPCsAEQEMFCsAAGQYAgUqY3RsMDAkQ29udGVudFBsYWNlSG9sZGVyQm9keSRlcnJvckdyaWR2aWV3D2dkBS9jdGwwMCRDb250ZW50UGxhY2VIb2xkZXJCb2R5JGd2SW52ZW50b3J5RGV0YWlscw88KwAMAQhmZOkI9SE%2BbDIhM1WxWrfOJW4h28SPp8qPpEvKt3GmM3xN",
		"--data", "__EVENTVALIDATION=%2FwEdAAsZV3%2FmZTG227Wf7PAYruT36NJMDzww3IJozuamiH2ntIYHsMIzYYJ%2BhEPXbUswhEgM%2BQi2wto3oIoOmOtZDQewMu1wDE8XlC69lmZmCD%2BHfJNQBJwY3SeA8fU%2FnTO3Cgd0dXDvR%2FgB01%2FGD3JYF0vk2B395ZvQbXFGN04uuEIz14KTWmUjUiEBImqToeuQtKrqZqEd5e1TGujvVLTXWKyhCPvlvwBboFdZ%2BtYjLeo3Nyy1ri%2BZNhH4hdQRjB9u3NpUzGZUWE5aH8oCv2VpyNu5",
	)
	return cmd.Output()
}
